import hashlib
import secrets
from collections.abc import Mapping
from datetime import datetime, timedelta, timezone
from typing import Any

import psycopg
from psycopg.rows import dict_row

from app.config import settings

Row = Mapping[str, Any]


def connect() -> psycopg.Connection:
    if not settings.database_url:
        raise RuntimeError("DATABASE_URL is required for Postgres storage.")
    return psycopg.connect(settings.database_url, row_factory=dict_row, prepare_threshold=None)


def init_db() -> None:
    with connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_setup (
                user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                cv_md TEXT NOT NULL DEFAULT '',
                profile_yml TEXT NOT NULL DEFAULT '',
                mode_profile_md TEXT NOT NULL DEFAULT '',
                portals_yml TEXT NOT NULL DEFAULT '',
                updated_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS usage_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                mode TEXT NOT NULL DEFAULT '',
                cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
                ok BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS usage_events_user_idx ON usage_events (user_id, created_at)"
        )


def hash_password(password: str, salt: str | None = None) -> str:
    salt = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 120_000)
    return f"pbkdf2_sha256${salt}${digest.hex()}"


def verify_password(password: str, stored: str) -> bool:
    try:
        _, salt, expected = stored.split("$", 2)
    except ValueError:
        return False
    actual = hash_password(password, salt).split("$", 2)[2]
    return secrets.compare_digest(actual, expected)


def create_user(email: str, password: str) -> Row:
    now = datetime.now(timezone.utc)
    with connect() as conn:
        user = conn.execute(
            """
            INSERT INTO users (email, password_hash, created_at)
            VALUES (%s, %s, %s)
            RETURNING id, email, created_at
            """,
            (email.lower().strip(), hash_password(password), now),
        ).fetchone()
        conn.execute(
            "INSERT INTO user_setup (user_id, updated_at) VALUES (%s, %s)",
            (user["id"], now),
        )
        return user


def find_user_by_email(email: str) -> Row | None:
    with connect() as conn:
        return conn.execute("SELECT * FROM users WHERE email = %s", (email.lower().strip(),)).fetchone()


def find_user_by_id(user_id: int) -> Row | None:
    with connect() as conn:
        return conn.execute("SELECT id, email, created_at FROM users WHERE id = %s", (user_id,)).fetchone()


def create_session(user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    expires = datetime.now(timezone.utc) + timedelta(days=14)
    with connect() as conn:
        conn.execute(
            "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (%s, %s, %s)",
            (token_hash, user_id, expires),
        )
    return token


def delete_session(token: str) -> None:
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    with connect() as conn:
        conn.execute("DELETE FROM sessions WHERE token_hash = %s", (token_hash,))


def user_from_session(token: str | None) -> Row | None:
    if not token:
        return None
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    now = datetime.now(timezone.utc)
    with connect() as conn:
        row = conn.execute(
            "SELECT user_id FROM sessions WHERE token_hash = %s AND expires_at > %s",
            (token_hash, now),
        ).fetchone()
    return find_user_by_id(row["user_id"]) if row else None


def record_usage(user_id: int, mode: str, cost_usd: float, ok: bool) -> None:
    now = datetime.now(timezone.utc)
    with connect() as conn:
        conn.execute(
            "INSERT INTO usage_events (user_id, mode, cost_usd, ok, created_at) VALUES (%s, %s, %s, %s, %s)",
            (user_id, mode or "", float(cost_usd or 0.0), bool(ok), now),
        )


def usage_total_usd(user_id: int) -> float:
    with connect() as conn:
        row = conn.execute(
            "SELECT COALESCE(SUM(cost_usd), 0) AS total FROM usage_events WHERE user_id = %s",
            (user_id,),
        ).fetchone()
    return float(row["total"]) if row else 0.0


def usage_today_usd(user_id: int) -> float:
    """Sum of a user's cost since UTC midnight (used for the daily budget gate)."""
    with connect() as conn:
        row = conn.execute(
            "SELECT COALESCE(SUM(cost_usd), 0) AS total FROM usage_events "
            "WHERE user_id = %s AND created_at >= date_trunc('day', now() AT TIME ZONE 'utc')",
            (user_id,),
        ).fetchone()
    return float(row["total"]) if row else 0.0


def get_setup(user_id: int) -> Row:
    now = datetime.now(timezone.utc)
    with connect() as conn:
        conn.execute(
            """
            INSERT INTO user_setup (user_id, updated_at)
            VALUES (%s, %s)
            ON CONFLICT (user_id) DO NOTHING
            """,
            (user_id, now),
        )
        return conn.execute("SELECT * FROM user_setup WHERE user_id = %s", (user_id,)).fetchone()


def update_setup(user_id: int, cv_md: str, profile_yml: str, mode_profile_md: str, portals_yml: str) -> Row:
    now = datetime.now(timezone.utc)
    with connect() as conn:
        return conn.execute(
            """
            INSERT INTO user_setup (user_id, cv_md, profile_yml, mode_profile_md, portals_yml, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id) DO UPDATE
            SET cv_md = EXCLUDED.cv_md,
                profile_yml = EXCLUDED.profile_yml,
                mode_profile_md = EXCLUDED.mode_profile_md,
                portals_yml = EXCLUDED.portals_yml,
                updated_at = EXCLUDED.updated_at
            RETURNING *
            """,
            (user_id, cv_md, profile_yml, mode_profile_md, portals_yml, now),
        ).fetchone()
